
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env  # Load environment variables from .env file
    volumes:
      - .:/app  # Mount the current directory to the container for live reloading
      - /app/node_modules  # Ensures Docker uses container’s node_modules
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/fadebowaley

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
     
volumes:
  mongo_data:
