version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env  # Load environment variables from .env file
    volumes:
      - .:/app  # Mount the current directory to the container for live reloading
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=your_username  # Optional
      - MONGO_INITDB_ROOT_PASSWORD=your_password  # Optional

volumes:
  mongo_data:
