name: CI/CD Pipeline

on:
  push:
    branches:
      - main            # Trigger this workflow on push to main branch
      - development      # Trigger this workflow on push to development branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # Updated to v3


      - name: Build Docker image
        run: docker build -t fadebowaley/proton:latest .

      - name: Push to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push fadebowaley/proton:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key for EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_proton
          chmod 600 ~/.ssh/id_rsa_proton
          ssh-keyscan -H 3.91.87.103  >> ~/.ssh/known_hosts
          ssh-keyscan -H 54.81.212.41 >> ~/.ssh/known_hosts

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/development'
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.81.212.41 << 'EOF'
            export MONGO_URI="${{ secrets.MONGO_URI }}"
            export SESSION_SECRET="${{ secrets.SESSION_SECRET }}"
            export MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}"
            export MAIL_USERNAME="${{ secrets.MAIL_USERNAME }}"
            export MAIL_SERVER="${{ secrets.MAIL_SERVER }}"
            export MAIL_PORT="${{ secrets.MAIL_PORT }}"
            export ADMIN_EMAIL="${{ secrets.ADMIN_EMAIL }}"
            export DEFAULT_SENDER="${{ secrets.DEFAULT_SENDER }}"
            export ORDER_SENDER="${{ secrets.ORDER_SENDER }}"
            export ACTIVATE_SENDER="${{ secrets.ACTIVATE_SENDER }}"
            export FEEDBACK_EMAIL="${{ secrets.FEEDBACK_EMAIL }}"
            docker pull fadebowaley/proton:latest
            docker-compose up -d
          EOF

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.91.87.103 << 'EOF'
            export MONGO_URI="${{ secrets.MONGO_URI }}"
            export SESSION_SECRET="${{ secrets.SESSION_SECRET }}"
            export MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}"
            export MAIL_USERNAME="${{ secrets.MAIL_USERNAME }}"
            export MAIL_SERVER="${{ secrets.MAIL_SERVER }}"
            export MAIL_PORT="${{ secrets.MAIL_PORT }}"
            export ADMIN_EMAIL="${{ secrets.ADMIN_EMAIL }}"
            export DEFAULT_SENDER="${{ secrets.DEFAULT_SENDER }}"
            export ORDER_SENDER="${{ secrets.ORDER_SENDER }}"
            export ACTIVATE_SENDER="${{ secrets.ACTIVATE_SENDER }}"
            export FEEDBACK_EMAIL="${{ secrets.FEEDBACK_EMAIL }}"
            docker pull fadebowaley/proton:latest
            docker-compose up -d
          EOF
